repo: pokedex

naming: true
restrictFileTypes: true
bestPractices: true

allFiles:

  html:
    valid: true
    bestPractices: true
    has:
      - ['title', 'Got to have a title on the page!']
      - ['body', 'It is not a website without a body!']
    hasNot:
      - ['br', 'If you are using hard line breaks, you can probably use margin to accomplish the same thing...']
      - ['hr', 'The `hr` tag should not be used to create borders']
  
html:
  - path: index.html
    has:
      - ['h1', 'Must have a h1 element!']
      - ['h2', 'Must have an h2 element']
      - ['p', 'Must have a paragraph element!']
      - ['table', 'Must be using a table to display the Pokemon']
    search:
      - ['Bulbasaur', 'You got to include my favorite pokemon!']
      
  - path: 'addpokemon.html'
    has:
      - ['form', 'Need to be using a form to add a new pokemon']
      - ['select[name="name"]', 'A select element must be present']
      - ['input[type="text"]', 'Need to keep track of a nickname with a text input!']
      - ['input[type="radio"][name="gender"]', 'Need to keep track of gender with a radio element']
      - ['input[type="submit"][value="Add Pokemon"]', 'Must be able to add a new pokemon to your collection with a submit button!']